FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    traceroute \
    net-tools \
    curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

CMD sysctl -p && tail -f /dev/null