FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    traceroute \
    net-tools \
    curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY entrypoint-router.sh /entrypoint-router.sh
RUN chmod +x /entrypoint-router.sh

ENTRYPOINT ["/entrypoint-router.sh"]