FROM nginx:alpine

RUN apk add --no-cache iproute2 iputils

RUN echo '#!/bin/sh\n' \
         'ip route add 192.168.10.0/24 via 192.168.20.2 || true\n' \
         'exec "$@"' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["tail", "-f", "/dev/null"]