FROM alpine:latest

RUN apk add --no-cache dnsmasq iproute2 iputils-ping curl net-tools

COPY dnsmaq.conf /etc/dnsmasq.conf

COPY entrypoint-server.sh /entrypoint-server.sh
RUN chmod +x /entrypoint-server.sh

EXPOSE 53/udp

ENTRYPOINT [ "/entrypoint-server.sh" ]