FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    net-tools \
    curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN echo '#!/bin/bash\n' \
         'ip route add 192.168.20.0/24 via 192.168.10.2 || true\n' \
         'exec "$@"' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["tail", "-f", "/dev/null"]